### PR TITLE
#431 - fix unable to upload file after clicking one file type then switching to another type

### LINKED ISSUE #431: unable to upload file after clicking one file type then switching to another type
I think the form just needs be updated on file type change, some uncompleted fields from previously selected types might be hanging around and causing the error.

**Steps to Reproduce**:

1.  At a site, go to the HWM tab and edit a HWM
2. Scroll to bottom, expand the HWM File Information section
3. Click 'Add File' button and then select 'Photo' as the file type. 
4. Then select 'Other' as the file type and complete all mandatory fields
5. Click 'Create File' and note that the error message pops up stating there are incomplete fields
image

### PR DESCRIPTION
**Pull request by Abigail770**

### CODE REVIEW

File: src/app/hwm-edit/hwm-edit.component.ts [hunk 1]
```diff
@@ -1080,6 +1086,7 @@ export class HwmEditComponent implements OnInit {
     let self = this;
     this.loading = true;
     this.hwmFileForm.markAllAsTouched();
+    console.log(this.hwmFileForm)
```
Comment (lprivette) [inline src/app/hwm-edit/hwm-edit.component.ts]:
```suggestion
```

**Review by lprivette — APPROVED** [review]

**Review by lprivette — APPROVED** [review]
