### PR TITLE
Fixes #23 - fixes networks filter

### LINKED ISSUE #23: Allow multiple networks to be selected
> Would it be possible to select multiple Network Names in STN?  That way ... the user can generate a map with all the Netwoks combined (i.e. show a national map).

### PR DESCRIPTION
**Pull request by 09Kathy**

### CODE REVIEW

File: src/app/map/map.component.ts [hunk 1]
```diff
@@ -973,65 +1006,141 @@ export class MapComponent implements OnInit {
...
-                        //if nothing is returned, show a snack bar message
-                        this.filtersSnackBar(
-                            'No results for your query. Try using fewer filters.',
-                            'OK',
-                            4500
-                        );
+            //network ids need to be called one at a time, so if there are multiple we put them in separate http requests
+            if (multiNetworkIds.length <= 1) {
+                // format url params into single string
+                let urlSingNetwork =
```
Comment (lprivette) [inline src/app/map/map.component.ts:1012]: Should this variable be called `urlStringNetwork`?

Comment (09Kathy) [reply src/app/map/map.component.ts:1012]: it was short for single (instead of multi). It didn't end up being necessary that those two variables have different names, so I can just change them back to the original

**Review by lprivette — APPROVED** [review]
