### PR TITLE
Fixes #163 - layer control works

### LINKED ISSUE #163: Fix site toggle
The Sites layer toggle is only connected to the event shown on map load. After applying filters, it doesn't work correctly. 
Steps to reproduce: 
-Refresh map
-Filter by SWATH network
-Toggle 'Sites' on an off. Notice that the initial event toggles on and off and other markers are unmoved.

### PR DESCRIPTION
**Pull request by 09Kathy**

### CODE REVIEW

File: src/app/map/map.component.ts [hunk 1]
```diff
@@ -246,7 +313,7 @@ export class MapComponent implements OnInit {
                 'descend'
             );
             //set up call to get sites for specific event
-            this.displaySelectedEvent();
+            this.displayMostRecentEvent();
```
Comment (lprivette) [inline src/app/map/map.component.ts:316]: good name change

**Review by lprivette — APPROVED** [review]
